tab = int(9)
print("Workshop 1 Part-2")
print("==========\n")
print("Using tab specifiers...")
print( chr(tab)+"Tab-1"+chr(tab)+"Tab-2"+chr(tab)+"Tab-3")
print(chr(tab)+"------"+chr(tab)+"====="+chr(tab)+"------\n")
print("\\this is a back-slash character!")
print("% this is a percent sign character!")
print("\" this is a double-quote character!\n")
print("My favourite quotes are:")
print("1."+chr(tab)+"\"Skill is only developed by hours and hours of work.\"")
print(chr(tab)+chr(tab)+chr(tab)+chr(tab)+chr(tab)+chr(tab)+"-Usain Bolt\n")
print("2."+chr(tab)+"\"It's not about having time. It's about making time.\"")
print(chr(tab)+chr(tab)+chr(tab)+chr(tab)+chr(tab)+chr(tab)+"-Unknown\n")
print("3."+chr(tab)+"\"All of us do not have equal talent. But, all of us\n"+chr(tab)+" have an equal opportunity to develop our talents.\"")
print(chr(tab)+chr(tab)+chr(tab)+chr(tab)+chr(tab)+chr(tab)+"-A.P.J. Abdul Kalam\n")
